@token=eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJpYXQiOjE3MTI1OTA3NzUsImp0aSI6Ik1xOFJEcEtlUXdJZXVTOHhGOUtOR1NVenRlYkNTSEdpOEh1clgzcytWVGs9IiwiaXNzIjoibHVtZW4tand0IiwibmJmIjoxNzEyNTkwNzc1LCJleHAiOjE3MTI2NzcxNzUsImRhdGEiOnsidXNlcklkIjoxLCJ1c3VhcmlvIjoiYWRtaW4ifX0.YbPEVlrUSjqpbGFfmZ6mL9jd3HAlovTyN-7s_jYUos8

### Obtener todas las asistencias
GET http://localhost:8082/asistencias
Authorization: Bearer {{token}}

### Obtener una asistencia específica
GET http://localhost:8080/asistencias/{id}
Authorization: Bearer {{token}}

### Crear una nueva asistencia
POST http://localhost:8080/asistencias
Authorization: Bearer {{token}}
Content-Type: application/json

{
    "visitante_id": 1,
    "fecha": "2022-01-01",
    "hora": "09:00:00"
}

### Actualizar una asistencia existente
PUT http://localhost:8080/asistencias/{id}
Authorization: Bearer {{token}}
Content-Type: application/json

{
    "visitante_id": 2,
    "fecha": "2022-01-02",
    "hora": "10:00:00"
}

### Eliminar una asistencia
DELETE http://localhost:8080/asistencias/{id}
Authorization: Bearer {{token}}
