### Obtener todos los usuarios
GET http://localhost:8080/users

### Crear un nuevo usuario
POST http://localhost:8080/users
Content-Type: application/json

{
    "dni": "40124010",
    "nombres": "Jose",
    "apellidos": "Perez",
    "rol": "admin",
    "usuario": "joseperez1",
    "password": "123456"
}

### Obtener un usuario por ID
GET http://localhost:8080/users/6

### Actualizar un usuario por ID
PUT http://localhost:8080/users/6
Content-Type: application/json

{
    "dni": "40124010",
    "nombres": "Jose",
    "apellidos": "Perez",
    "rol": "admin",
    "usuario": "joseperez2",
    "password": "123456"
}

### Eliminar un usuario por ID
DELETE http://localhost:8080/users/6
