@token=eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJpYXQiOjE3MTIzNTEyNzUsImp0aSI6Ild1RXhUL2FzaXV3dmhmMzg0N1lsU3JVWWZ5a2hQcTlZclhJczM5Nk91RnM9IiwiaXNzIjoibHVtZW4tand0IiwibmJmIjoxNzEyMzUxMjc1LCJleHAiOjE3MTI0Mzc2NzUsImRhdGEiOnsidXNlcklkIjoxLCJ1c3VhcmlvIjoiYWRtaW4ifX0.98QYIMe8vaLSgaRC33sq6znEwGk5lI4VYYak8tu1tcw

### Obtener todos los usuarios
GET http://localhost:8080/users
Authorization: Bearer {{token}}

### Crear un nuevo usuario
POST http://localhost:8080/users
Authorization: Bearer {{token}}
Content-Type: application/json

{
    "dni": "40124010",
    "nombres": "Jose",
    "apellidos": "Perez",
    "rol": "admin",
    "usuario": "joseperez1",
    "password": "123456"
}

### Obtener un usuario por ID
GET http://localhost:8080/users/6
Authorization: Bearer {{token}}

### Actualizar un usuario por ID
PUT http://localhost:8080/users/6
Authorization: Bearer {{token}}
Content-Type: application/json

{
    "dni": "40124010",
    "nombres": "Jose",
    "apellidos": "Perez",
    "rol": "admin",
    "usuario": "joseperez2",
    "password": "123456"
}

### Eliminar un usuario por ID
DELETE http://localhost:8080/users/6
Authorization: Bearer {{token}}
