@token=eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJpYXQiOjE3MTI1MDE1MDUsImp0aSI6IlovZFdWejFadDlUOWxaK0xtNFNPK0hvRWpXbER6VmdmZjVrNGZkbThjRjg9IiwiaXNzIjoibHVtZW4tand0IiwibmJmIjoxNzEyNTAxNTA1LCJleHAiOjE3MTI1ODc5MDUsImRhdGEiOnsidXNlcklkIjoxLCJ1c3VhcmlvIjoiYWRtaW4ifX0.f66EA7iu54bcc3azrVe4mi6vvI1lag0YUD1YNSmHCuE

### Obtener todos los visitantes
GET http://localhost:8080/visitantes
Authorization: Bearer {{token}}

### Parámetros de consulta opcionales:
- perPage: número de elementos por página (por defecto: 10)
- query: consulta de búsqueda

### Crear un nuevo visitante
POST http://localhost:8080/visitantes
Authorization: Bearer {{token}}
Content-Type: application/json

{
    "dni": "12345678",
    "ap_paterno": "Pérez",
    "ap_materno": "Gómez",
    "nombres": "Juan"
}

### Obtener un visitante por ID
GET http://localhost:8080/visitantes/1
Authorization: Bearer {{token}}

### Obtener un visitante por DNI
GET http://localhost:8080/visitantes/70693076/dni
Authorization: Bearer {{token}}

### Obtener un visitante por RUC
GET http://localhost:8080/visitantes/10447359982/ruc
Authorization: Bearer {{token}}

### Actualizar un visitante existente
PUT http://localhost:8080/visitantes/1
Authorization: Bearer {{token}}

### Cuerpo de la solicitud:
{
    "dni": "87654321",
    "ap_paterno": "Gómez",
    "ap_materno": "Pérez",
    "nombres": "Juan"
}

### Eliminar un visitante
DELETE http://localhost:8080/visitantes/1
Authorization: Bearer {{token}}
