@token=eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJpYXQiOjE3MTIzNTEyNzUsImp0aSI6Ild1RXhUL2FzaXV3dmhmMzg0N1lsU3JVWWZ5a2hQcTlZclhJczM5Nk91RnM9IiwiaXNzIjoibHVtZW4tand0IiwibmJmIjoxNzEyMzUxMjc1LCJleHAiOjE3MTI0Mzc2NzUsImRhdGEiOnsidXNlcklkIjoxLCJ1c3VhcmlvIjoiYWRtaW4ifX0.98QYIMe8vaLSgaRC33sq6znEwGk5lI4VYYak8tu1tcw

### Obtener todos los visitantes
GET http://localhost:8080/visitantes
Authorization: Bearer {{token}}

### Parámetros de consulta opcionales:
- perPage: número de elementos por página (por defecto: 10)
- query: consulta de búsqueda

### Crear un nuevo visitante
POST http://localhost:8080/visitantes
Authorization: Bearer {{token}}
Content-Type: application/json

{
    "dni": "12345678",
    "ap_paterno": "Pérez",
    "ap_materno": "Gómez",
    "nombres": "Juan"
}

### Obtener un visitante por ID
GET http://localhost:8080/visitantes/1
Authorization: Bearer {{token}}

### Actualizar un visitante existente
PUT http://localhost:8080/visitantes/1
Authorization: Bearer {{token}}

### Cuerpo de la solicitud:
{
    "dni": "87654321",
    "ap_paterno": "Gómez",
    "ap_materno": "Pérez",
    "nombres": "Juan"
}

### Eliminar un visitante
DELETE http://localhost:8080/visitantes/1
Authorization: Bearer {{token}}
